# 47장 에러 처리

## 목차

1. [에러 처리의 필요성](#1-에러-처리의-필요성)
2. [try...catch...finally 문](#2-try...catch...finally-문)
3. [Error 객체](#3-Error-객체)
4. [throw 문](#4-throw-문)
5. [에러의 전파](#5-에러의-전파)

<br />


## 1. 에러 처리의 필요성
- 에러가 없는 코드를 작성하는 것은 불가능 합니다. 따라서, 에러가 발생했을 때를 대비하는 코드도 작성해야 합니다. 만약, 그렇지 않을 경우, 프로그램은 강제 종료 됩니다.

<br />

## 2. try...catch...finally 문
- 에러를 처리하는 방법은 2가지가 있습니다.
- 첫 번째 방법은 예외 상황이 발생하면, 반환 값을 null, -1, 옵셔널 체이닝을 통해, 에러를 처리하는 방법입니다. (문제는, 개발자가 예상하지 못한 에러에는 대비되지 않는다는 점입니다.)
- 두 번째 방법은 try...catch...finally 문입니다.
- try 문 블록이 시작된 후, 만약 해당 블록 내부에서 에러가 발생할 경우, catch 문에 에러를 전달하고, catch 블록이 실행됩니다.

<br />

## 3. Error 객체
- Error 생성자 함수는 에러 객체를 생성합니다. Error 생성자 함수를 통해, 에러를 상세히 설명할 수 있습니다.
- message 프로퍼티는 Error 생성자 함수에 인수로 전달한 에러 메시지이고, stack 프로퍼티의 값은 에러를 발생시킨 콜스택의 호출 정보를 문자열로 보여줍니다.
- Error 생성자 함수 뿐만 아니라, 7가지의 에러 생성자 함수를 제공합니다.

<br />

## 4. throw 문
- Error 생성자 함수로 에러 객체를 생성 시, 에러가 바로 발생하지는 않습니다. **생성**과 **발생**은 다릅니다.
- 에러를 발생시키면, try 코드 블록에서 throw 문으로 에러 객체를 던져야 합니다.

<br />

## 5. 에러의 전파
- 45.1.2절 "에러 처리의 한계"에서 살펴본 바와 같이, 에러는 호출자 (자신을 호출한 상위 컨택스트, 콜스택 아래에 위치)방향으로 전파됩니다.
- throw 된 에러가 상위 호출자로 던진 후, 상위 호출자가 이를 catch 하지 않는다면, 다음 호출자 방향으로 전파됩니다.